CREATE TABLE `intakeSessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionToken` varchar(64) NOT NULL,
	`status` enum('intake','waiting','consulting','survey','completed') NOT NULL DEFAULT 'intake',
	`nameKana` varchar(128),
	`name` varchar(128),
	`birthDate` date,
	`postalCode` varchar(10),
	`address` text,
	`phone` varchar(20),
	`mobile` varchar(20),
	`email` varchar(320),
	`occupation` varchar(128),
	`referrer` varchar(128),
	`consultationReason` text,
	`caseId` int,
	`surveyResponseId` int,
	`exportedToSalesforce` boolean DEFAULT false,
	`exportedAt` timestamp,
	`intakeCompletedAt` timestamp,
	`consultationStartedAt` timestamp,
	`consultationCompletedAt` timestamp,
	`surveyCompletedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intakeSessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `intakeSessions_sessionToken_unique` UNIQUE(`sessionToken`)
);
